# This query will work on sparql-endpoint if their triple store have used rdf-schema.

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


SELECT ?subject ?property
WHERE{ 
  ?subject rdfs:subClassOf ?property 
}