# Retrieve chembl molecule activity details for all target

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dbpedia2: <http://dbpedia.org/property/>
PREFIX dbpedia: <http://dbpedia.org/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX cco: <http://rdf.ebi.ac.uk/terms/chembl#>


SELECT ?chembl_id ?std_value ?std_unit ?std_type ?std_rel ?ass_disc
WHERE {
  ?molecule cco:hasActivity ?act.
  ?molecule rdfs:subClassOf cco:Substance. 
  ?molecule rdfs:label ?chembl_id .
  ?act cco:hasAssay ?ass.
  ?act cco:standardValue ?std_value .
  ?act cco:standardUnits ?std_unit .
  ?act cco:standardType ?std_type .
  ?act cco:standardRelation ?std_rel.
  ?ass dcterms:description ?ass_disc.
  ?ass cco:hasTarget ?tar.
  ?tar rdfs:label ?tar_id .
}
